import Sidebar from '@/components/Sidebar'
import Head from 'next/head'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='container'>
       <div className='main-container'>
       <div className='sidebar'>
        <Sidebar/>
       </div>
        <div className='main-content'>
          <h1>Hello word</h1>
        </div>
        </div>
      </main>
    </>
  )
}
